// Language pipeline contracts for Haskell and Nix (CORE-003).
//
// Three jobs, all additive over the existing finding / component / scan-health /
// DataFlowGraph shapes (no required field is removed or renamed):
//
//   1. METADATA. Optional `language`, `capability`, `evidenceKind`, `scope`,
//      `uncertainty` and `originalLocation` fields, validated by
//      validateLanguageFinding / validateLanguageComponent. `parser`/`family`
//      stay required exactly as before.
//   2. PRODUCERS. Every language analyzer is registered (with the shared
//      pipeline/producer-registry.js as well as a local table that carries the
//      capability and evidence kinds). A finding from an unregistered producer
//      is dropped from the result and recorded as an `unregistered-producer`
//      outcome, so it cannot silently reach a verdict.
//   3. COVERAGE OUTCOMES. runLanguageAnalysis drives registered adapters over a
//      file set and records, per file and per analyzer, exactly one of
//      analyzed / excluded / unresolved / failed / timed_out / missing_grammar.
//      reconcileLanguageLedger proves those counts add up to the real inputs.
//      languageHealth turns the ledger into scan-health conditions.
//
// Nothing here executes scanned code: adapters are caller-supplied functions
// over file text.

import { isRegisteredProducer, registerProducer } from '../pipeline/producer-registry.js';
import { isLanguageExcludedPath, isLanguageSource, languageOf } from './discovery.js';

export const LANGUAGE_CONTRACT_VERSION = 1;

export const LANGUAGES = Object.freeze(['haskell', 'nix']);

/**
 * `type` of a supply-chain entry that is a build/fetch/cache TRUST finding rather than an
 * advisory match (NIX-005). It travels in the same `supplyChain` bucket as `vulnerable_dep`,
 * so SCA policy, SCA verdicts and scan health read it without a side channel.
 */
export const BUILD_TRUST_TYPE = 'nix_build_trust';

// Evidence kinds. For Nix, a script generated by a derivation, the static
// configuration it declares, and observed runtime state are different claims
// and must never share a kind.
export const EVIDENCE_KINDS = Object.freeze([
  'source', 'manifest', 'lock', 'config', 'generated-script', 'runtime',
]);

export const CAPABILITIES = Object.freeze([
  'parse', 'sast', 'taint', 'sca', 'config', 'iac', 'privacy', 'route-inventory',
]);

export const FILE_STATUSES = Object.freeze([
  'analyzed', 'excluded', 'unresolved', 'failed', 'timed_out', 'missing_grammar',
]);

// Why an outcome was recorded. `unresolved-branch` is a file that WAS analyzed
// but left a branch the adapter could not resolve; it is reported on top of the
// file's status, not instead of it.
export const OUTCOME_KINDS = Object.freeze([
  'missing-grammar', 'adapter-exception', 'unresolved-branch', 'timeout',
  'unregistered-producer', 'excluded-path', 'unsupported-language',
]);

export const UNCERTAINTY_KINDS = Object.freeze([
  'unresolved-import', 'unresolved-branch', 'generated-source', 'preprocessed', 'partial-parse',
  // a call whose target is not known (higher-order parameter, unbound name, typeclass without a visible
  // instance) or whose code is not analysed (foreign function): taint is widened across it, never dropped
  'unresolved-target', 'foreign-boundary',
  // the analysed library version is not one the model was written against: results are best-effort
  'untested-model',
]);

// ── 2. producers ───────────────────────────────────────────────────────────

const _producers = new Map();

/**
 * @param {object} def
 * @param {string} def.id            unique, `language:<name>` by convention
 * @param {string} def.language      one of LANGUAGES
 * @param {string} def.capability    one of CAPABILITIES
 * @param {string[]} [def.evidenceKinds]  subset of EVIDENCE_KINDS it may emit
 * @param {string} [def.version]
 */
export function registerLanguageProducer(def) {
  if (!def || typeof def !== 'object') throw new Error('registerLanguageProducer: definition required');
  const { id, language, capability, evidenceKinds = ['source'], version = '1' } = def;
  if (typeof id !== 'string' || !id) throw new Error('registerLanguageProducer: id required');
  if (!LANGUAGES.includes(language)) throw new Error(`registerLanguageProducer: "${id}" unknown language "${language}"`);
  if (!CAPABILITIES.includes(capability)) throw new Error(`registerLanguageProducer: "${id}" unknown capability "${capability}"`);
  for (const k of evidenceKinds) {
    if (!EVIDENCE_KINDS.includes(k)) throw new Error(`registerLanguageProducer: "${id}" unknown evidence kind "${k}"`);
  }
  if (_producers.has(id)) throw new Error(`registerLanguageProducer: duplicate producer id "${id}"`);
  _producers.set(id, Object.freeze({ id, language, capability, evidenceKinds: Object.freeze([...evidenceKinds]), version }));
  if (!isRegisteredProducer(id)) registerProducer({ id, version, phase: 'sast', languages: [language] });
  return _producers.get(id);
}

export function isRegisteredLanguageProducer(id) {
  return _producers.has(id);
}

export function listLanguageProducers() {
  return [..._producers.values()];
}

/** Test-only. */
export function _resetLanguageProducersForTests() {
  _producers.clear();
}

// ── 1. metadata + validators ───────────────────────────────────────────────

const REQUIRED_FINDING_FIELDS = ['id', 'severity', 'file', 'line', 'vuln', 'cwe', 'description', 'remediation', 'parser', 'family'];
const SEVERITIES = ['critical', 'high', 'medium', 'low', 'info'];

function validLocation(loc) {
  return !!loc && typeof loc === 'object'
    && Number.isInteger(loc.line) && loc.line >= 1
    && (loc.column === undefined || (Number.isInteger(loc.column) && loc.column >= 0))
    && (loc.file === undefined || typeof loc.file === 'string');
}

function validateLanguageFields(obj, errors, label) {
  if (obj.language !== undefined && !LANGUAGES.includes(obj.language)) errors.push(`${label}: unknown language "${obj.language}"`);
  if (obj.capability !== undefined && !CAPABILITIES.includes(obj.capability)) errors.push(`${label}: unknown capability "${obj.capability}"`);
  if (obj.evidenceKind !== undefined && !EVIDENCE_KINDS.includes(obj.evidenceKind)) errors.push(`${label}: unknown evidenceKind "${obj.evidenceKind}"`);
  if (obj.scope !== undefined) {
    const s = obj.scope;
    if (!s || typeof s !== 'object' || Array.isArray(s)) errors.push(`${label}: scope must be an object`);
    else {
      for (const k of ['target', 'configuration', 'component']) {
        if (s[k] !== undefined && s[k] !== null && typeof s[k] !== 'string') errors.push(`${label}: scope.${k} must be a string or null`);
      }
    }
  }
  if (obj.uncertainty !== undefined) {
    if (!Array.isArray(obj.uncertainty)) errors.push(`${label}: uncertainty must be an array`);
    else {
      for (const u of obj.uncertainty) {
        if (!u || !UNCERTAINTY_KINDS.includes(u.kind)) errors.push(`${label}: unknown uncertainty kind "${u && u.kind}"`);
      }
    }
  }
  if (obj.originalLocation !== undefined && !validLocation(obj.originalLocation)) errors.push(`${label}: originalLocation needs an integer line >= 1`);
}

/**
 * Validates the finding contract. The legacy required fields are unchanged, so
 * an output written before this contract existed still validates; the language
 * fields are checked only when present. `producer`, when present, must be
 * registered.
 */
export function validateLanguageFinding(f) {
  const errors = [];
  if (!f || typeof f !== 'object') return { valid: false, errors: ['finding must be an object'] };
  for (const k of REQUIRED_FINDING_FIELDS) {
    if (f[k] === undefined || f[k] === null || f[k] === '') {
      // `line` may legitimately be null for struct detectors, but then it is not suppressible; keep it required here.
      errors.push(`missing required field "${k}"`);
    }
  }
  if (f.severity !== undefined && !SEVERITIES.includes(f.severity)) errors.push(`invalid severity "${f.severity}"`);
  validateLanguageFields(f, errors, 'finding');
  if (f.producer !== undefined && !isRegisteredLanguageProducer(f.producer)) errors.push(`finding: producer "${f.producer}" is not registered`);
  return { valid: errors.length === 0, errors };
}

/** Component contract (SBOM/inventory entry). Legacy `name` + `version` stay required. */
export function validateLanguageComponent(c) {
  const errors = [];
  if (!c || typeof c !== 'object') return { valid: false, errors: ['component must be an object'] };
  if (typeof c.name !== 'string' || !c.name) errors.push('missing required field "name"');
  if (c.version !== undefined && c.version !== null && typeof c.version !== 'string') errors.push('component: version must be a string or null');
  validateLanguageFields(c, errors, 'component');
  return { valid: errors.length === 0, errors };
}

/** Adds language metadata to a finding without overwriting detector-set values. */
export function withLanguageMetadata(finding, meta = {}) {
  const out = { ...finding };
  const lang = out.language ?? meta.language ?? languageOf(out.file || '');
  if (lang) out.language = lang;
  for (const k of ['capability', 'evidenceKind', 'scope', 'uncertainty', 'originalLocation', 'producer']) {
    if (out[k] === undefined && meta[k] !== undefined) out[k] = meta[k];
  }
  return out;
}

// ── 3. coverage outcomes ───────────────────────────────────────────────────

function emptyCounts() {
  return { discovered: 0, analyzed: 0, excluded: 0, unresolved: 0, failed: 0, timedOut: 0, missingGrammar: 0 };
}

const STATUS_COUNT_KEY = {
  analyzed: 'analyzed', excluded: 'excluded', unresolved: 'unresolved',
  failed: 'failed', timed_out: 'timedOut', missing_grammar: 'missingGrammar',
};

function withTimeout(promiseLike, ms) {
  if (!Number.isFinite(ms) || ms <= 0) return Promise.resolve(promiseLike);
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => reject(Object.assign(new Error(`timed out after ${ms}ms`), { code: 'LANG_TIMEOUT' })), ms);
  });
  return Promise.race([Promise.resolve(promiseLike), timeout]).finally(() => clearTimeout(timer));
}

/**
 * Drives registered adapters over a file set.
 *
 * @param {object} input
 * @param {Record<string,string>} input.files  rel path -> content (the real inputs)
 * @param {Array<{id:string, language:string, hasGrammar?:()=>boolean,
 *   analyze:(file:string, content:string)=>({findings?:object[], unresolved?:object[]}|Promise<object>)}>} input.adapters
 * @param {number} [input.timeoutMs]
 * @returns {Promise<{findings:object[], ledger:object, outcomes:object[]}>}
 *   ledger.byFile[file][analyzerId] is a status string; ledger.byAnalyzer[id] holds counts.
 */
export async function runLanguageAnalysis({ files = {}, adapters = [], timeoutMs = 0 } = {}) {
  const findings = [];
  const outcomes = [];
  const byFile = {};
  const byAnalyzer = {};
  const discoveredFiles = [];
  const excludedFiles = [];

  for (const a of adapters) byAnalyzer[a.id] = { language: a.language, ...emptyCounts() };

  for (const rel of Object.keys(files).sort()) {
    const lang = languageOf(rel);
    if (!lang || !isLanguageSource(rel)) continue; // manifests and unrelated files are not analyzer inputs
    if (isLanguageExcludedPath(rel)) {
      excludedFiles.push(rel);
      outcomes.push({ kind: 'excluded-path', file: rel, language: lang });
      continue;
    }
    discoveredFiles.push(rel);
    byFile[rel] = {};
    const applicable = adapters.filter((a) => a.language === lang);
    if (!applicable.length) {
      outcomes.push({ kind: 'unsupported-language', file: rel, language: lang });
      continue;
    }
    for (const a of applicable) {
      const counts = byAnalyzer[a.id];
      counts.discovered += 1;
      const setStatus = (status) => { byFile[rel][a.id] = status; counts[STATUS_COUNT_KEY[status]] += 1; };

      if (!isRegisteredLanguageProducer(a.id)) {
        // Unregistered producers never contribute findings; the file is unresolved, not clean.
        setStatus('unresolved');
        outcomes.push({ kind: 'unregistered-producer', file: rel, analyzer: a.id, language: lang });
        continue;
      }
      if (typeof a.hasGrammar === 'function' && !a.hasGrammar()) {
        setStatus('missing_grammar');
        outcomes.push({ kind: 'missing-grammar', file: rel, analyzer: a.id, language: lang });
        continue;
      }
      let result;
      try {
        result = await withTimeout(a.analyze(rel, files[rel]), timeoutMs);
      } catch (err) {
        if (err && err.code === 'LANG_TIMEOUT') {
          setStatus('timed_out');
          outcomes.push({ kind: 'timeout', file: rel, analyzer: a.id, language: lang, detail: String(err.message) });
        } else {
          setStatus('failed');
          outcomes.push({ kind: 'adapter-exception', file: rel, analyzer: a.id, language: lang, detail: String((err && err.message) || err) });
        }
        continue;
      }
      const producer = _producers.get(a.id);
      for (const f of (result && result.findings) || []) {
        findings.push(withLanguageMetadata(f, { language: lang, capability: producer.capability, producer: a.id }));
      }
      const unresolved = (result && result.unresolved) || [];
      for (const u of unresolved) {
        outcomes.push({ kind: 'unresolved-branch', file: rel, analyzer: a.id, language: lang, line: Number.isInteger(u.line) ? u.line : null, detail: u.reason || null });
      }
      // A file with an unresolved branch was read but is not fully understood.
      setStatus(unresolved.length ? 'unresolved' : 'analyzed');
    }
  }

  return { findings, ledger: { byFile, byAnalyzer, discoveredFiles, excludedFiles }, outcomes };
}

/**
 * Checks that ledger counts reconcile with the real inputs: every discovered
 * file has exactly one status per applicable analyzer, per-analyzer counts equal
 * the sum of its statuses, and discovered + excluded equals the language
 * sources actually present in `files`.
 * @returns {{ok:boolean, errors:string[]}}
 */
export function reconcileLanguageLedger(ledger, files) {
  const errors = [];
  const real = Object.keys(files).filter((k) => isLanguageSource(k));
  const accounted = new Set([...ledger.discoveredFiles, ...ledger.excludedFiles]);
  if (accounted.size !== ledger.discoveredFiles.length + ledger.excludedFiles.length) errors.push('a file is both discovered and excluded');
  for (const k of real) if (!accounted.has(k)) errors.push(`input file "${k}" is not accounted for`);
  for (const k of accounted) if (!real.includes(k)) errors.push(`ledger file "${k}" is not a real input`);

  for (const [id, c] of Object.entries(ledger.byAnalyzer)) {
    const sum = c.analyzed + c.excluded + c.unresolved + c.failed + c.timedOut + c.missingGrammar;
    if (sum !== c.discovered) errors.push(`analyzer "${id}": statuses sum to ${sum}, discovered ${c.discovered}`);
    let fromFiles = 0;
    for (const row of Object.values(ledger.byFile)) if (row[id] !== undefined) fromFiles += 1;
    if (fromFiles !== c.discovered) errors.push(`analyzer "${id}": ${fromFiles} per-file rows, discovered ${c.discovered}`);
  }
  for (const [file, row] of Object.entries(ledger.byFile)) {
    for (const [id, status] of Object.entries(row)) {
      if (!FILE_STATUSES.includes(status)) errors.push(`file "${file}" analyzer "${id}": unknown status "${status}"`);
    }
  }
  return { ok: errors.length === 0, errors };
}

/**
 * Converts a run's ledger + outcomes into the shape computeScanHealth accepts as
 * `languageCoverage`: totals plus human-readable conditions. Only an
 * all-analyzed run with no unresolved branch is `complete`.
 */
export function languageHealth({ ledger, outcomes }) {
  const totals = emptyCounts();
  for (const c of Object.values(ledger.byAnalyzer)) {
    for (const k of Object.keys(totals)) totals[k] += c[k];
  }
  totals.excluded += ledger.excludedFiles.length;
  const byKind = {};
  for (const o of outcomes) byKind[o.kind] = (byKind[o.kind] || 0) + 1;
  const conditions = [];
  if (byKind['missing-grammar']) conditions.push(`${byKind['missing-grammar']} language file(s) skipped: grammar unavailable`);
  if (byKind['adapter-exception']) conditions.push(`${byKind['adapter-exception']} language adapter exception(s)`);
  if (byKind['timeout']) conditions.push(`${byKind['timeout']} language file(s) timed out`);
  if (byKind['unresolved-branch']) conditions.push(`${byKind['unresolved-branch']} unresolved language branch(es)`);
  if (byKind['unregistered-producer']) conditions.push(`${byKind['unregistered-producer']} result(s) from an unregistered language producer were discarded`);
  return { schemaVersion: LANGUAGE_CONTRACT_VERSION, totals, byKind, conditions };
}
