// Artifact registry + registry-driven reset tests (assurance-hardening PRD,
// Milestone 0/1, FR-701/FR-703).
//
// `cmdReset` had NO test coverage at all before this file — a real gap given
// it deletes files. These tests cover both the registry module directly and
// the actual `reset` CLI command end-to-end via a spawned subprocess against
// a synthetic `.agentic-security/` directory.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as fsp from 'node:fs/promises';
import * as path from 'node:path';
import * as os from 'node:os';
import {
  ARTIFACT_REGISTRY, listGeneratedArtifacts, listOperatorConfigArtifacts,
  isRegisteredArtifact, classificationOf,
} from '../src/posture/artifact-registry.js';

const SCANNER = path.resolve(process.cwd());
const CLI = path.join(SCANNER, 'bin', 'agentic-security.js');

test('ARTIFACT_REGISTRY: no duplicate names', () => {
  const names = ARTIFACT_REGISTRY.map(a => a.name);
  assert.deepEqual(names, [...new Set(names)]);
});

test('ARTIFACT_REGISTRY: every entry has a valid classification and kind', () => {
  for (const a of ARTIFACT_REGISTRY) {
    assert.ok(['generated', 'operator-config'].includes(a.classification), `bad classification for ${a.name}`);
    assert.ok(['file', 'dir'].includes(a.kind), `bad kind for ${a.name}`);
  }
});

test('the A-10-evidenced missing artifacts are now registered as generated', () => {
  // These were confirmed (by reading their actual write call sites) to be
  // scanner-generated output missing from the old hardcoded WIPE list.
  for (const name of [
    'dpia.md', 'privacy-framework.json', 'privacy-framework.md',
    'ifds-summaries.json', 'exploit-bundles.json', 'cve-alerts-state.json',
    'compliance-evidence.json', 'compliance-evidence.md', 'ATTRIBUTIONS.md',
    'accepted.json', 'triage.json', 'pqc-migration-plan.json', 'pqc-migration-plan.md',
  ]) {
    assert.equal(classificationOf(name), 'generated', `expected ${name} to be registered as generated`);
  }
});

test('artifacts that looked generated by name but are actually operator/agent-authored input are classified operator-config, not generated', () => {
  // Corrections made during this audit — see artifact-registry.js's header.
  // Getting these wrong (classifying as 'generated') would make `reset`
  // delete real input data, a worse bug than the one being fixed.
  for (const name of ['logic-claims.json', 'current-intent.md', 'exploit-history.jsonl', 'cve-alerts.json', 'network-policy.json']) {
    assert.equal(classificationOf(name), 'operator-config', `expected ${name} to be preserved, not wiped`);
  }
});

test('isRegisteredArtifact / classificationOf return null-ish for unknown names', () => {
  assert.equal(isRegisteredArtifact('totally-unknown-file.xyz'), false);
  assert.equal(classificationOf('totally-unknown-file.xyz'), null);
});

test('listGeneratedArtifacts and listOperatorConfigArtifacts partition the registry with no overlap', () => {
  const gen = new Set(listGeneratedArtifacts().map(a => a.name));
  const cfg = new Set(listOperatorConfigArtifacts().map(a => a.name));
  assert.equal(gen.size + cfg.size, ARTIFACT_REGISTRY.length);
  for (const name of gen) assert.ok(!cfg.has(name), `${name} appears in both partitions`);
});

function makeFixtureProject() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agentic-security-reset-test-'));
  fs.writeFileSync(path.join(root, 'package.json'), '{"name":"fixture"}\n');
  const stateDir = path.join(root, '.agentic-security');
  fs.mkdirSync(stateDir, { recursive: true });
  return { root, stateDir };
}

function writeState(stateDir, relPath, content = '{}') {
  const full = path.join(stateDir, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
}

function runReset(root, extraArgs = []) {
  return spawnSync(process.execPath, [CLI, 'reset', '--root', root, ...extraArgs], {
    cwd: SCANNER, encoding: 'utf8', timeout: 30_000,
  });
}

test('reset (end-to-end): removes previously-missed generated artifacts and preserves operator-config', () => {
  const { root, stateDir } = makeFixtureProject();
  try {
    // A generated artifact already in the old hardcoded list.
    writeState(stateDir, 'last-scan.json', '{"findings":[]}');
    // Generated artifacts the OLD hardcoded WIPE list missed (A-10) — the
    // actual bug this cycle fixes.
    writeState(stateDir, 'dpia.md', '# DPIA\n');
    writeState(stateDir, 'privacy-framework.json', '{}');
    writeState(stateDir, 'exploit-bundles.json', '{}');
    writeState(stateDir, 'accepted.json', '[]');
    // Operator/agent-authored input that must survive reset.
    writeState(stateDir, 'rules.yml', 'custom: []\n');
    writeState(stateDir, 'risk-config.yml', 'impactUSD: {}\n');
    writeState(stateDir, 'logic-claims.json', '[]');
    writeState(stateDir, 'exploit-history.jsonl', '{}\n');
    writeState(stateDir, 'network-policy.json', '{"workloads":{}}');

    const run = runReset(root, ['--yes']);
    assert.equal(run.status, 0, `reset failed: ${run.stderr}`);

    const remaining = fs.readdirSync(stateDir);
    // Generated (including the previously-missed ones) must be GONE.
    for (const gone of ['last-scan.json', 'dpia.md', 'privacy-framework.json', 'exploit-bundles.json', 'accepted.json']) {
      assert.ok(!remaining.includes(gone), `expected ${gone} to be removed by reset, remaining: ${JSON.stringify(remaining)}`);
    }
    // Operator-config must SURVIVE.
    for (const kept of ['rules.yml', 'risk-config.yml', 'logic-claims.json', 'exploit-history.jsonl', 'network-policy.json']) {
      assert.ok(remaining.includes(kept), `expected ${kept} to survive reset, remaining: ${JSON.stringify(remaining)}`);
    }
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('reset: dry-run (no --yes) deletes nothing', () => {
  const { root, stateDir } = makeFixtureProject();
  try {
    writeState(stateDir, 'last-scan.json', '{}');
    writeState(stateDir, 'dpia.md', '# DPIA\n');
    const run = runReset(root);
    assert.equal(run.status, 0);
    const remaining = fs.readdirSync(stateDir);
    assert.ok(remaining.includes('last-scan.json'));
    assert.ok(remaining.includes('dpia.md'));
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('reset: --keep spares an explicitly named generated artifact', () => {
  const { root, stateDir } = makeFixtureProject();
  try {
    writeState(stateDir, 'last-scan.json', '{}');
    writeState(stateDir, 'dpia.md', '# DPIA\n');
    const run = runReset(root, ['--yes', '--keep', 'dpia.md']);
    assert.equal(run.status, 0, run.stderr);
    const remaining = fs.readdirSync(stateDir);
    assert.ok(!remaining.includes('last-scan.json'));
    assert.ok(remaining.includes('dpia.md'), '--keep should have spared dpia.md');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('reset: an unregistered, unknown file is left untouched (unknown is not the same as generated)', () => {
  const { root, stateDir } = makeFixtureProject();
  try {
    writeState(stateDir, 'some-future-artifact-nobody-registered-yet.json', '{}');
    const run = runReset(root, ['--yes']);
    assert.equal(run.status, 0, run.stderr);
    const remaining = fs.readdirSync(stateDir);
    assert.ok(remaining.includes('some-future-artifact-nobody-registered-yet.json'),
      'an unregistered artifact must not be silently deleted by classification guesswork');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

// Sub-project E, increment 5, final-review MUST-FIX 1: lineage-graph.json +
// its .sig were written by bin/agentic-security.js but never registered
// here, so `reset` treated them as unregistered/unknown and preserved them
// under the "Preserving operator-authored config: ..." message — the
// opposite of correct for a scanner-GENERATED artifact that can carry
// dataElements[].dataClasses derived from the user's own source. Proven
// live against an unpatched worktree before this fix (reset preserved
// both files); this test pins the fixed behavior so it cannot regress.
test('reset: lineage-graph.json + .sig are registered as generated and ARE wiped by reset --yes (MF-1)', () => {
  const { root, stateDir } = makeFixtureProject();
  try {
    writeState(stateDir, 'last-scan.json', '{"findings":[]}');
    writeState(stateDir, 'lineage-graph.json', '{"schemaVersion":"1.0.0","nodes":[],"edges":[],"dataElements":[],"flows":[]}');
    writeState(stateDir, 'lineage-graph.json.sig', 'deadbeef');

    const dry = runReset(root);
    assert.equal(dry.status, 0, dry.stderr);
    assert.ok(dry.stdout.includes('lineage-graph.json'), 'dry-run must list lineage-graph.json as a removal target');
    assert.ok(dry.stdout.includes('lineage-graph.json.sig'), 'dry-run must list lineage-graph.json.sig as a removal target');
    assert.ok(!dry.stdout.includes('Preserving operator-authored config: lineage-graph.json'),
      'lineage-graph.json must never be reported as preserved operator-authored config');

    const run = runReset(root, ['--yes']);
    assert.equal(run.status, 0, run.stderr);
    const remaining = fs.readdirSync(stateDir);
    assert.ok(!remaining.includes('lineage-graph.json'), `expected lineage-graph.json to be removed, remaining: ${JSON.stringify(remaining)}`);
    assert.ok(!remaining.includes('lineage-graph.json.sig'), `expected lineage-graph.json.sig to be removed, remaining: ${JSON.stringify(remaining)}`);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});
