// Pure builders for the support registry and its rendered table: shared by promote.mjs (which writes them) and check.mjs (which
// recomputes them from the stored measurement and fails on any difference).
import { evaluateSupport, checkPromotion, verifyRegistry, SUPPORT_REGISTRY_VERSION, TARGETS, PAIR_GATE } from '../../scanner/src/language/support-registry.js';
import { HS_PACKAGES, HS_WEB_FRAMEWORKS } from '../../scanner/src/language/haskell-models.js';

export const LIMITS = Object.freeze([
  'The corpus is synthetic and template-generated (QA-001): holdout cases vary nouns, fields and paths over the SAME shapes as the development cases, so a holdout score measures robustness to those variations, not accuracy on arbitrary real-world code.',
  'No real-world canary projects and no real advisory records beyond the pinned HSEC fixtures are in the measurement: real-project accuracy is NOT measured.',
  'No GHC, cabal, stack or nix is installed where the measurement ran: compile-based verification, optional Nix evaluation and any NixOS host behaviour are blocked, never reported as passing.',
  'Findings of a different family inside a case are reported separately (family-scoped scoring); the strict precision, which counts them, is stored next to every layer.',
  'Parameters of an exported Haskell function are treated as caller-controlled text or customer records: a flow from such a parameter is reported with that source label, which is a weaker claim than a request or stdin read.',
]);

/** @returns {{registry: object, allSupported: boolean}} */
export function buildRegistry(measurement, suites, frozen, probe) {
  const tools = suites.tools || probe || {};
  const registry = { schema: 'agentic-security/language-support@1', version: SUPPORT_REGISTRY_VERSION, generatedAt: measurement.measuredAt, node: suites.node, targets: TARGETS, pairGate: PAIR_GATE, languages: {} };
  let allSupported = true;
  for (const language of ['haskell', 'nix']) {
    const evaluated = evaluateSupport(language, { measurement, suites: suites.results, capabilitySuites: suites.capabilitySuites[language], tools, frozen });
    const rows = {};
    for (const [cap, r] of Object.entries(evaluated.rows)) {
      const check = checkPromotion(language, cap, r.status, r.evidence, evaluated);
      if (!check.ok) { r.status = 'unverified'; r.reasons = [...r.reasons, ...check.reasons]; }
      rows[cap] = r;
    }
    allSupported = allSupported && Object.values(rows).every((r) => r.status === 'supported');
    const eco = measurement.ecosystems[language] || {};
    registry.languages[language] = {
      frozen, measuredOn: { split: measurement.split, measuredAt: measurement.measuredAt, corpusVersion: measurement.corpusVersion, hashes: measurement.hashes, corpusTotals: measurement.corpusTotals[language] },
      rows, summary: evaluated.summary, metamorphic: evaluated.metamorphic || null,
      unknownOutcomes: eco.detection ? eco.detection.unknownOutcomes : null,
      modelledVersions: language === 'haskell' ? { packages: Object.fromEntries(Object.entries(HS_PACKAGES).map(([k, v]) => [k, v.tested])), webFrameworks: Object.fromEntries(Object.entries(HS_WEB_FRAMEWORKS).map(([k, v]) => [k, v.tested])) } : null,
    };
  }
  registry.tools = tools;
  registry.limits = [...LIMITS];
  registry.verified = verifyRegistry(registry, frozen);
  return { registry, allSupported };
}

const pct = (x) => (x == null ? 'n/a' : `${(x * 100).toFixed(1)}%`);

export function renderTable(registry) {
  const first = Object.values(registry.languages)[0];
  const lines = ['# Haskell and Nix support', '', `Generated by \`node bench/language-support/promote.mjs\` from the frozen holdout (corpus ${first.frozen.corpusVersion}, measured ${registry.generatedAt}). Do not edit by hand.`, '', 'A row is **supported** only from passing evidence of its own metric kind. Read the limits below before quoting any number.', ''];
  for (const [lang, entry] of Object.entries(registry.languages)) {
    lines.push(`## ${lang === 'haskell' ? 'Haskell' : 'Nix and NixOS'}`, '', '| Capability | Status | Evidence | Why not supported |', '|---|---|---|---|');
    for (const r of Object.values(entry.rows)) {
      const e = r.evidence || {};
      const ev = e.precision !== undefined ? `P ${pct(e.precision)} / R ${pct(e.recall)} / F1 ${pct(e.f1)} (${e.tp ?? '?'} TP, ${e.fp ?? '?'} FP, ${e.fn ?? '?'} FN)` : e.manifests ? `manifests ${e.manifests}; advisory ranges ${e.advisoryRanges ?? 'n/a'}` : e.accepted ? `accepted ${e.accepted}; rejected ${e.rejected}; advertised ${e.advertised}` : e.parsed !== undefined ? `${e.parsed}/${e.files} parsed; ${e.crashed} crashed` : '';
      lines.push(`| ${r.capability} | ${r.status} | ${ev} | ${(r.reasons || []).slice(0, 2).join('; ').replace(/\|/g, '/')} |`);
    }
    const u = entry.unknownOutcomes;
    lines.push('', `Unknown and unmodelled cases: ${u ? `${u.total} total, ${u.silentClean} silent-clean (false assurance), ${u.requiredDisclosureMissing} undisclosed required boundary` : 'not measured'}.`);
    if (entry.metamorphic) lines.push(`Metamorphic pairs: semantics-changing ${pct(entry.metamorphic.change)}, semantics-preserving ${pct(entry.metamorphic.preserve)} (this project's own gate; the PRD sets none).`);
    lines.push('');
  }
  lines.push('## Limits', '', ...registry.limits.map((l) => `- ${l}`), '');
  return `${lines.join('\n')}\n`;
}
