// export-privacy.js — Milestone 4 deliverable #10 (DFG-020): graph-derived
// DPIA/RoPA export, migrating off the Layer-2 taint engine's
// dataflow/privacy-taint.js#emitDpiaArtifact / privacy-governance.js#emitRopaArtifact
// (which derive from piiFields, name-in-argument classification with no
// path/alias/field-mapping precision) onto the real DataFlowGraph v1's
// field-identity-tracked flows.
//
// Reuses frontend/src/views/privacy-view.js#computePrivacyViewModel
// DIRECTLY (the first live scanner/ -> frontend/ module import in this
// codebase, confirmed safe: that module only touches document/window
// inside renderPrivacyView's own function body, never at module top
// level, so importing it from plain Node never executes any DOM code)
// rather than re-deriving lifecycle-stage/dataClass/protection-verdict
// row computation a second time. This mirrors this package's own
// established discipline of reusing an already-correct, already-tested
// computation rather than a parallel copy that can drift.
//
// Both emit functions mirror their taint-engine-era predecessors'
// structure/wording (GDPR Art. 35 framing for the DPIA, the
// register-not-narrative RoPA table) but are populated from real graph
// rows.
//
// Filter wiring: opts.filter is the SAME {nodeIds, edgeIds} shape every
// other `dataflow export` format uses (export-json.js's own convention).
// It filters the GRAPH itself, via export-json.js's _filterGraph, BEFORE
// computePrivacyViewModel ever runs — never threaded into
// computePrivacyViewModel's own state.filters parameter, which expects a
// completely different shape (per-facet selected-value arrays, e.g.
// {dataClass: [...]}) and would silently no-op if handed {nodeIds, edgeIds}.

import { computePrivacyViewModel } from '../../../frontend/src/views/privacy-view.js';
import { GOVERNANCE_FIELDS, MANUAL_REQUIRED } from '../dataflow/privacy-governance.js';
import { _filterGraph } from './export-json.js';

function _emptyState() {
  return { selectedId: null };
}

function _scopedViewModel(graph, filter) {
  const scopedGraph = filter ? _filterGraph(graph, filter) : graph;
  return computePrivacyViewModel(scopedGraph, _emptyState(), null);
}

/** Group computePrivacyViewModel's rows by data class, mirroring emitDpiaArtifact's own grouping. */
function _groupRowsByClass(rows) {
  const grouped = new Map();
  for (const row of rows) {
    for (const cls of row.dataClasses) {
      let g = grouped.get(cls);
      if (!g) { g = []; grouped.set(cls, g); }
      g.push(row);
    }
  }
  return grouped;
}

/**
 * Graph-derived DPIA (Data Protection Impact Assessment) — narrative
 * Markdown, mirroring dataflow/privacy-taint.js#emitDpiaArtifact's own
 * structure. opts.filter scopes to a subset of the graph (the "filtered
 * ... from the selected graph scope" requirement, PRD 7.4).
 */
export function emitGraphDpiaArtifact(graph, opts = {}) {
  const viewModel = _scopedViewModel(graph, opts.filter);
  const visibleRows = viewModel.rows.filter((r) => r.visible !== false);
  const grouped = _groupRowsByClass(visibleRows);

  const lines = [];
  lines.push('# Data Protection Impact Assessment (DPIA)');
  lines.push('');
  lines.push(`Generated by agentic-security scanner (graph-derived) on ${(opts.generatedAt ?? new Date().toISOString()).slice(0, 10)}.`);
  lines.push('');
  lines.push('This is an automated DPIA scaffold derived from real data-flow analysis');
  lines.push('(field identity, path provenance, and protection verdicts). It must be');
  lines.push('reviewed and completed by a privacy officer before use.');
  lines.push('');
  if (grouped.size === 0) {
    lines.push('No regulated data classes were identified in this graph scope.');
    return lines.join('\n');
  }
  lines.push('## Data classes identified');
  lines.push('');
  for (const [cls, rows] of grouped) {
    lines.push(`### ${cls} (${rows.length} flow(s))`);
    lines.push('');
    for (const row of rows.slice(0, 20)) {
      lines.push(`- \`${row.dataElementName}\` — ${row.sourceCategory ?? 'unknown source'} -> ${row.sinkCategory ?? 'unknown sink'} (protection: ${row.protectionSummary})`);
    }
    if (rows.length > 20) lines.push(`- ... and ${rows.length - 20} more`);
    lines.push('');
    lines.push(`**Governance fields for ${cls}:**`);
    lines.push('');
    // Worst-case-wins across this class's own rows, the same tie-break
    // Task 1's resolveGovernanceRefs default uses — never silently pick
    // whichever row happened to be iterated last.
    const merged = {};
    for (const row of rows) {
      for (const field of GOVERNANCE_FIELDS) {
        const r = row.governanceRefs?.[field];
        if (!r) continue;
        if (!merged[field] || merged[field].source === 'manual_required') merged[field] = r;
      }
    }
    for (const field of GOVERNANCE_FIELDS) {
      const r = merged[field] ?? { value: MANUAL_REQUIRED, source: 'manual_required' };
      lines.push(`- ${field}: \`${r.value}\`${r.source === 'operator_provided' ? ' (operator-provided)' : ''}`);
    }
    lines.push('');
  }
  lines.push('## Regulatory framework mapping');
  lines.push('');
  lines.push('- **GDPR Art. 35** — DPIA required when processing is likely to result in high risk to data subjects.');
  lines.push('- **CCPA 1798.130** — Notice + access rights for collected personal information.');
  if (grouped.has('PHI')) lines.push('- **HIPAA 164.308** — Administrative safeguards for ePHI access.');
  if (grouped.has('PCI')) lines.push('- **PCI DSS Req. 3** — Protect stored cardholder data.');
  lines.push('');
  lines.push('This document organizes automated technical assessment evidence. It does');
  lines.push("not certify compliance and is not a legal determination — see the graph's");
  lines.push('own `disclaimer`/`limitations` fields for the full caveat.');
  return lines.join('\n');
}

/**
 * Graph-derived RoPA (Record of Processing Activities, GDPR Art. 30) —
 * tabular Markdown register, mirroring
 * dataflow/privacy-governance.js#emitRopaArtifact's own format, but ONE
 * ROW PER (dataClass x flow) rather than per dataClass alone — a real,
 * disclosed precision improvement the graph's own per-flow sink/
 * destination resolution makes possible (the taint-engine version has no
 * per-flow destination-resolution concept at all).
 */
export function emitGraphRopaArtifact(graph, opts = {}) {
  const viewModel = _scopedViewModel(graph, opts.filter);
  const visibleRows = viewModel.rows.filter((r) => r.visible !== false);

  const lines = [];
  lines.push('# Record of Processing Activities (RoPA) — GDPR Art. 30, graph-derived');
  lines.push('');
  lines.push('Generated by agentic-security scanner (graph-derived). Every governance');
  lines.push('field below is either supplied by an operator');
  lines.push('(.agentic-security/privacy-governance.json) or marked');
  lines.push(`\`${MANUAL_REQUIRED}\` — none are inferable from source code, and none are`);
  lines.push(`guessed. A privacy officer must fill in every \`${MANUAL_REQUIRED}\` cell`);
  lines.push('before this document is usable as a real RoPA.');
  lines.push('');
  if (visibleRows.length === 0) {
    lines.push('No regulated data flows were identified in this graph scope.');
    return lines.join('\n');
  }
  const header = ['Data class', 'Field', 'Source', 'Destination', 'Protection', ...GOVERNANCE_FIELDS];
  lines.push(`| ${header.join(' | ')} |`);
  lines.push(`|${header.map(() => '---').join('|')}|`);
  let gapCount = 0;
  for (const row of visibleRows) {
    for (const cls of row.dataClasses.length ? row.dataClasses : ['(unclassified)']) {
      const fieldValues = GOVERNANCE_FIELDS.map((f) => {
        const r = row.governanceRefs?.[f] ?? { value: MANUAL_REQUIRED, source: 'manual_required' };
        if (r.source === 'manual_required') gapCount++;
        return r.value;
      });
      lines.push(`| ${[cls, row.dataElementName, row.sourceCategory ?? 'unknown', row.sinkCategory ?? 'unknown', row.protectionSummary, ...fieldValues].join(' | ')} |`);
    }
  }
  lines.push('');
  lines.push(`${gapCount} field(s) across ${visibleRows.length} flow(s) require manual input.`);
  return lines.join('\n');
}
